// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrwmtazuoebcefycuhus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yd210YXp1b2ViY2VmeWN1aHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDY3MzAsImV4cCI6MjA2MzM4MjczMH0.bmN-yeUpHIN_a32izbwJBnxfuXVn84KHgj1A_ompsRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);